apiVersion: v1
kind: Service
metadata:
  name: nszpc-service
  namespace: nszpc
spec:
  type: NodePort
  selector:
    app: nszpc
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
